# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Peter M. Attia
email: peter.m.attia@gmail.com
description: Batteries, electrochemistry, machine learning, and more
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://petermattia.com"
google_analytics: G-SGFLS2X2L8
linkedin_username: peter-m-attia
github_username:  petermattia
gscholar_username:  GyD43R4AAAAJ
orcid: 0000-0003-4745-5726

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate-v2

pagination:
  enabled: true
  per_page: 8
  collection: 'posts'
  permalink: '/page/:num/'
  sort_field: 'date'
  sort_reverse: true

collections:
  cyclic_voltammetry_simulation:
    output: true
    permalink: /:collection/:name
  galvanostatic_simulation:
      output: true
      permalink: /:collection/:name

# Exclude from processing.
# The following items will not be processed, by default.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - deploy.sh
  - s3_website.yml
